// A small example board that exercises every helper in space.mjs.
// Copy this file as a starting point for your own generated boards.

export function drawDemo(space) {
  const SANS = 'sans'

  space.text({ x: 40, y: 40, text: 'excalidraw space', size: 'xl', font: SANS })
  space.text({
    x: 40, y: 110, width: 900, size: 'm', color: 'grey', font: SANS,
    text: 'This board was generated by a script. Drag anything — your edits save back to space.excalidraw, and a script can read them again.',
  })

  // A band with shapes sitting on top of it.
  space.rect({ x: 40, y: 200, w: 900, h: 240, color: 'blue', fill: 'semi', opacity: 0.15 })
  space.text({ x: 65, y: 218, text: 'shapes', size: 's', color: 'blue', font: SANS })

  space.rect({ x: 80, y: 270, w: 200, h: 120, text: 'rectangle', color: 'blue', font: SANS })
  space.ellipse({ x: 320, y: 270, w: 200, h: 120, text: 'ellipse', color: 'green', font: SANS })
  space.diamond({ x: 560, y: 270, w: 200, h: 120, text: 'diamond', color: 'violet', font: SANS })

  space.arrow({ from: { x: 290, y: 330 }, to: { x: 310, y: 330 }, color: 'grey' })
  space.arrow({ from: { x: 530, y: 330 }, to: { x: 550, y: 330 }, color: 'grey' })

  // Wrapped body text: space.mjs hard-wraps standalone text to the given width.
  space.text({
    x: 40, y: 490, width: 900, size: 's', color: 'black', font: SANS,
    text: 'Text bound inside a shape wraps on its own. Standalone text does not re-flow in Excalidraw, so space.mjs wraps it for you when you pass a width — which is why this paragraph breaks where it does.',
  })
}
